<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-20170725TZYG" name="127.0.0.1:21503" tests="1" failures="1" timestamp="28 Sep 2017 10:08:05 GMT" time="2.196" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="cn.crazy.appium.testcases.LoginRegister">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at cn.crazy.appium.testcases.LoginRegister.afterMethod(LoginRegister.java:152)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="regCase" time="0.008" classname="cn.crazy.appium.testcases.LoginRegister">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at cn.crazy.appium.testcases.LoginRegister.regCase(LoginRegister.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- regCase -->
</testsuite> <!-- 127.0.0.1:21503 -->
